# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU


API_KEY: 05add59ce93c7ff0b3d9eec68a38813f
SHARED_SECRET: 8d13733bf783be98

ACCESS_TOKEN: 72157677177494336-9f61b91015123d90
ACCESS_SECRET: d2ba16ecf5770788
